CC		=	clang++
CFLAGS	=	-std=c++17 -g


find_first_elem: 
	$(CC) $(CFLAGS) $@.cpp -o $@

group_str_for_prefix: 
	$(CC) $(CFLAGS) $@.cpp -o $@

group_str_by_prefix2: 
	$(CC) $(CFLAGS) $@.cpp -o $@

name_and_surname: 
	$(CC) $(CFLAGS) $@.cpp -o $@

fclean:
	rm -rf find_first_elem group_str_for_prefix name_and_surname group_str_by_prefix2
